#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi

if [[ "$( file -Lb --mime-type "$file")" =~ ^video ]]; then
    thumb="$HOME/.cache/lf_thumbnailer/$(echo "$file" | tr '/ ' '-x')_thumbnail.png"
    if [ ! -f $thumb ]; then
        # create thumbnail
        ffmpeg -ss 00:00:01.000 -i "$file" -vframes 1 "$thumb" 1> /dev/null 2> /dev/null
    fi
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$thumb" < /dev/null > /dev/tty
    exit 1
fi

pistol "$file"
